login: &login
  adapter: mysql
  username: root
  password: 
  #host: mysql.example.com

development:
  <<: *login
  database: cp_dev

test:
  <<: *login
  database: cp_test

production:
  <<: *login
  database: cp_prod

